export default {
  CAST: { label: 'Caste' },
  DSCR: { label: 'Physical Description' },
  EDUC: { label: 'Education' },
  FACT: { label: 'Fact' },
  IDNO: { label: 'ID Number' },
  NATI: { label: 'Nationality' },
  NCHI: { label: 'Number of Children' },
  NMR: { label: 'Number of Marriages' },
  OCCU: { label: 'Occupation' },
  PROP: { label: 'Property' },
  RELI: { label: 'Religion' },
  RESI: { label: 'Residence' },
  SSN: { label: 'Social Security Number' },
  TITL: { label: 'Title' },
};
